export const cameraTypes = [
  {
    id: 'L-C920',
    brand: 'Logitech',
    type: 'Webcam C920',
    isSupported: true,
  },
  {
    id: 'L-C920e',
    brand: 'Logitech',
    type: 'Webcam C920e',
    isSupported: true,
  },
  {
    id: 'L-C505',
    brand: 'Logitech',
    type: 'Webcam C505',
    isSupported: false,
  },
  {
    id: 'L-PTZPro2',
    brand: 'Logitech',
    type: 'PTZ Pro 2',
    sSupported: true,
  },
  {
    id: 'L-C270',
    brand: 'Logitech',
    type: 'HD Webcam C270',
    isSupported: true,
  },
  {
    id: 'L-C930e',
    brand: 'Logitech',
    type: 'Webcam C930e',
    isSupported: true,
  },
  {
    id: 'L-C920s',
    brand: 'Logitech',
    type: 'Webcam C920s',
    isSupported: true,
  },
  {
    id: 'G-ECam8000',
    brand: 'Genius',
    type: 'ECam 8000',
    isSupported: true,
  },
  {
    id: 'G-QCam6000',
    brand: 'Genius',
    type: 'QCam 6000',
    isSupported: false,
  },
  {
    id: 'G-FCam1000x2',
    brand: 'Genius',
    type: 'FaceCam 1000X v2',
    isSupported: true,
  },
  {
    id: 'M-LifeCamCin',
    brand: 'Microsoft',
    type: 'LifeCam Cinema',
    isSupported: false,
  },
  // {
  //   id: 4,
  //   brand: 'A4Tech',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 5,
  //   brand: 'BML',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 6,
  //   brand: 'C -TEC',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 7,
  //   brand: 'Grandstream',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 8,
  //   brand: 'Hikvision',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 9,
  //   brand: 'KBpro',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 10,
  //   brand: 'Niceboy',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 11,
  //   brand: 'Poly',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 12,
  //   brand: 'Razer',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 13,
  //   brand: 'Rollei',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 14,
  //   brand: 'Sandberg',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 15,
  //   brand: 'SWISSTEN',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 16,
  //   brand: 'Trust',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 17,
  //   brand: 'UNIBOS',
  //   type: '',
  //   isSupported: true,
  // },
  // {
  //   id: 18,
  //   brand: 'VIVOLINK',
  //   type: '',
  //   isSupported: true,
  // },
];
